# Generated by Django 5.1.2 on 2024-11-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texts',
            name='path',
        ),
        migrations.RemoveField(
            model_name='texts',
            name='text',
        ),
        migrations.AddField(
            model_name='texts',
            name='component',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='texts',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='texts',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texts',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texts',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
