# Generated by Django 5.1.2 on 2024-11-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_texts_path_remove_texts_text_texts_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='artistname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='texts',
            name='photourl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
