# Generated by Django 5.1.2 on 2024-11-04 09:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_texts_artistname_alter_texts_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=list, size=None),
        ),
    ]
