# Generated by Django 5.1.2 on 2024-11-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_instruments_features_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=25)),
                ('photourl', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
    ]
