# Generated by Django 5.1.2 on 2024-11-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_instrumentlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentlisting',
            name='link',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
