# Generated by Django 5.1.2 on 2024-11-13 13:12

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_instrumentlisting_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='img_url',
            new_name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='title',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='url',
        ),
        migrations.AddField(
            model_name='clients',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='clients',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
